


name: Terraform Destroy

# This will provide manual trigger event, every time we create push a commit.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch: # # Allows manual triggering


env:            
  AWS_REGION: us-east-1  

jobs:
  CICD-DESTROY-ECS:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
   
    - name: Terraform Init
      run: terraform init
   
    - name: Terraform Destroy
      run: terraform destroy --auto-approve