name: Terraform Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "ECR image tag (e.g. github.sha)"
        required: true

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: my-ecs-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR URI
        id: ecr
        run: |
          ECR_URI=$(aws ecr describe-repositories --repository-names ${PROJECT_NAME}-repo --query "repositories[0].repositoryUri" --output text)
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      - name: Terraform Init & Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="ecr_repository_url=${{ env.ECR_URI }}" \
            -var="image_tag=${{ github.event.inputs.image_tag }}"
